site_name: beta-kde
repo_url: https://github.com/egonmedhatten/beta-kde

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections

# Extensions for Math and Permalinks
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list

# JavaScript for MathJax (Rendering the math)
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Theory: theory.md
  - API Reference: api.md

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/beta-kde/
      name: PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/egonmedhatten/beta-kde
      name: GitHub