[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "beta-kde"
version = "0.1.2"
description = "Beta Kernel Density Estimation with automatic bandwidth selection, compatible with Scikit-learn"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "BSD-3-Clause"}
authors = [
  {name = "Johan Hallberg Szabadvary", email = "johan.hallberg.szabadvary@ju.se"}
]
dependencies = [
    "numpy>=1.20",
    "scipy>=1.7",
    "scikit-learn>=1.0",
    "matplotlib>=3.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["kernel-density-estimation", "kde", "beta-kernel", "bounded-data", "scikit-learn"]

[project.urls]
"Homepage" = "https://github.com/egonmedhatten/beta-kde"
"Documentation" = "https://egonmedhatten.github.io/beta-kde/" 
"Bug Tracker" = "https://github.com/egonmedhatten/beta-kde/issues"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "ruff",
    "build",
    "twine",
    "leancheck"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
# Always run with coverage for the src/beta_kde package and show missing lines
addopts = "--cov=src/beta_kde --cov-report=term-missing"
testpaths = ["tests"]